#!/bin/bash
# 2023-DEC-03 CRW
# Install HomeBrew (brew), package manager for MacOS (community-only version of yum/apt)

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# These are the autogenerated environment-addition lines from the HomeBrew installation
#
# They are run here to save the trouble, this will just make the "brew" command
#   available at the CLI for the remaining steps.

(
    echo
    echo 'eval "$(/opt/homebrew/bin/brew shellenv)"'
) >>~/.zprofile

eval "$(/opt/homebrew/bin/brew shellenv)"

echo "HomeBrew is now installed"

# Install Ansible via HomeBrew
#
# This is to keep it installed system-wide, decoupling it from any Python considerations
#   such as virtual environments or version mis-matches

brew install ansible

echo "Ansible (via HomeBrew) is now installed"

ansible-galaxy collection install community.general

echo "localhost ansible_connection=local ansible_user=$(whoami)" >>localhost

ansible-playbook -i localhost macos-setup-playbook.yml

# Install oh-my-zsh

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
